/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.mathCompiler;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mathCompiler.MathExp#getAbstractExpression <em>Abstract Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mathCompiler.MathCompilerPackage#getMathExp()
 * @model
 * @generated
 */
public interface MathExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Abstract Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.mathCompiler.AbstractExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Expression</em>' containment reference list.
   * @see org.xtext.example.mydsl.mathCompiler.MathCompilerPackage#getMathExp_AbstractExpression()
   * @model containment="true"
   * @generated
   */
  EList<AbstractExpression> getAbstractExpression();

} // MathExp
