/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.mathCompiler.AbstractExpression;
import org.xtext.example.mydsl.mathCompiler.Div;
import org.xtext.example.mydsl.mathCompiler.Let;
import org.xtext.example.mydsl.mathCompiler.MathCompilerPackage;
import org.xtext.example.mydsl.mathCompiler.MathExp;
import org.xtext.example.mydsl.mathCompiler.Minus;
import org.xtext.example.mydsl.mathCompiler.Mod;
import org.xtext.example.mydsl.mathCompiler.Mult;
import org.xtext.example.mydsl.mathCompiler.Num;
import org.xtext.example.mydsl.mathCompiler.Plus;
import org.xtext.example.mydsl.mathCompiler.Pow;
import org.xtext.example.mydsl.mathCompiler.Var;
import org.xtext.example.mydsl.services.MathCompilerGrammarAccess;

@SuppressWarnings("all")
public class MathCompilerSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MathCompilerGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MathCompilerPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MathCompilerPackage.ABSTRACT_EXPRESSION:
				sequence_AbstractExpression(context, (AbstractExpression) semanticObject); 
				return; 
			case MathCompilerPackage.DIV:
				sequence_Factor(context, (Div) semanticObject); 
				return; 
			case MathCompilerPackage.LET:
				sequence_VariableBinding(context, (Let) semanticObject); 
				return; 
			case MathCompilerPackage.MATH_EXP:
				sequence_MathExp(context, (MathExp) semanticObject); 
				return; 
			case MathCompilerPackage.MINUS:
				sequence_Exp(context, (Minus) semanticObject); 
				return; 
			case MathCompilerPackage.MOD:
				sequence_Top(context, (Mod) semanticObject); 
				return; 
			case MathCompilerPackage.MULT:
				sequence_Factor(context, (Mult) semanticObject); 
				return; 
			case MathCompilerPackage.NUM:
				sequence_Number(context, (Num) semanticObject); 
				return; 
			case MathCompilerPackage.PLUS:
				sequence_Exp(context, (Plus) semanticObject); 
				return; 
			case MathCompilerPackage.POW:
				sequence_Top(context, (Pow) semanticObject); 
				return; 
			case MathCompilerPackage.VAR:
				sequence_VariableUse(context, (Var) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AbstractExpression returns AbstractExpression
	 *
	 * Constraint:
	 *     (label=STRING exp=Exp)
	 */
	protected void sequence_AbstractExpression(ISerializationContext context, AbstractExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.ABSTRACT_EXPRESSION__LABEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.ABSTRACT_EXPRESSION__LABEL));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.ABSTRACT_EXPRESSION__EXP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.ABSTRACT_EXPRESSION__EXP));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAbstractExpressionAccess().getLabelSTRINGTerminalRuleCall_0_0(), semanticObject.getLabel());
		feeder.accept(grammarAccess.getAbstractExpressionAccess().getExpExpParserRuleCall_1_0(), semanticObject.getExp());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Minus
	 *     Exp.Plus_1_0_0_1 returns Minus
	 *     Exp.Minus_1_0_1_1 returns Minus
	 *     Factor returns Minus
	 *     Factor.Mult_1_0_0_1 returns Minus
	 *     Factor.Div_1_0_1_1 returns Minus
	 *     Top returns Minus
	 *     Top.Pow_1_0_0_1 returns Minus
	 *     Top.Mod_1_0_1_1 returns Minus
	 *     Primary returns Minus
	 *     Parenthesis returns Minus
	 *
	 * Constraint:
	 *     (left=Exp_Minus_1_0_1_1 right=Factor)
	 */
	protected void sequence_Exp(ISerializationContext context, Minus semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.MINUS__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.MINUS__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.MINUS__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.MINUS__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExpAccess().getMinusLeftAction_1_0_1_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getExpAccess().getRightFactorParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Plus
	 *     Exp.Plus_1_0_0_1 returns Plus
	 *     Exp.Minus_1_0_1_1 returns Plus
	 *     Factor returns Plus
	 *     Factor.Mult_1_0_0_1 returns Plus
	 *     Factor.Div_1_0_1_1 returns Plus
	 *     Top returns Plus
	 *     Top.Pow_1_0_0_1 returns Plus
	 *     Top.Mod_1_0_1_1 returns Plus
	 *     Primary returns Plus
	 *     Parenthesis returns Plus
	 *
	 * Constraint:
	 *     (left=Exp_Plus_1_0_0_1 right=Factor)
	 */
	protected void sequence_Exp(ISerializationContext context, Plus semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.PLUS__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.PLUS__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.PLUS__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.PLUS__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExpAccess().getPlusLeftAction_1_0_0_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getExpAccess().getRightFactorParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Div
	 *     Exp.Plus_1_0_0_1 returns Div
	 *     Exp.Minus_1_0_1_1 returns Div
	 *     Factor returns Div
	 *     Factor.Mult_1_0_0_1 returns Div
	 *     Factor.Div_1_0_1_1 returns Div
	 *     Top returns Div
	 *     Top.Pow_1_0_0_1 returns Div
	 *     Top.Mod_1_0_1_1 returns Div
	 *     Primary returns Div
	 *     Parenthesis returns Div
	 *
	 * Constraint:
	 *     (left=Factor_Div_1_0_1_1 right=Top)
	 */
	protected void sequence_Factor(ISerializationContext context, Div semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.DIV__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.DIV__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.DIV__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.DIV__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFactorAccess().getDivLeftAction_1_0_1_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getFactorAccess().getRightTopParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Mult
	 *     Exp.Plus_1_0_0_1 returns Mult
	 *     Exp.Minus_1_0_1_1 returns Mult
	 *     Factor returns Mult
	 *     Factor.Mult_1_0_0_1 returns Mult
	 *     Factor.Div_1_0_1_1 returns Mult
	 *     Top returns Mult
	 *     Top.Pow_1_0_0_1 returns Mult
	 *     Top.Mod_1_0_1_1 returns Mult
	 *     Primary returns Mult
	 *     Parenthesis returns Mult
	 *
	 * Constraint:
	 *     (left=Factor_Mult_1_0_0_1 right=Top)
	 */
	protected void sequence_Factor(ISerializationContext context, Mult semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.MULT__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.MULT__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.MULT__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.MULT__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFactorAccess().getMultLeftAction_1_0_0_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getFactorAccess().getRightTopParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     MathExp returns MathExp
	 *
	 * Constraint:
	 *     (abstractExpression+=AbstractExpression abstractExpression+=AbstractExpression*)
	 */
	protected void sequence_MathExp(ISerializationContext context, MathExp semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Num
	 *     Exp.Plus_1_0_0_1 returns Num
	 *     Exp.Minus_1_0_1_1 returns Num
	 *     Factor returns Num
	 *     Factor.Mult_1_0_0_1 returns Num
	 *     Factor.Div_1_0_1_1 returns Num
	 *     Top returns Num
	 *     Top.Pow_1_0_0_1 returns Num
	 *     Top.Mod_1_0_1_1 returns Num
	 *     Primary returns Num
	 *     Parenthesis returns Num
	 *     Number returns Num
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_Number(ISerializationContext context, Num semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.NUM__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.NUM__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNumberAccess().getValueINTTerminalRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Mod
	 *     Exp.Plus_1_0_0_1 returns Mod
	 *     Exp.Minus_1_0_1_1 returns Mod
	 *     Factor returns Mod
	 *     Factor.Mult_1_0_0_1 returns Mod
	 *     Factor.Div_1_0_1_1 returns Mod
	 *     Top returns Mod
	 *     Top.Pow_1_0_0_1 returns Mod
	 *     Top.Mod_1_0_1_1 returns Mod
	 *     Primary returns Mod
	 *     Parenthesis returns Mod
	 *
	 * Constraint:
	 *     (left=Top_Mod_1_0_1_1 right=Primary)
	 */
	protected void sequence_Top(ISerializationContext context, Mod semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.MOD__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.MOD__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.MOD__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.MOD__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTopAccess().getModLeftAction_1_0_1_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getTopAccess().getRightPrimaryParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Pow
	 *     Exp.Plus_1_0_0_1 returns Pow
	 *     Exp.Minus_1_0_1_1 returns Pow
	 *     Factor returns Pow
	 *     Factor.Mult_1_0_0_1 returns Pow
	 *     Factor.Div_1_0_1_1 returns Pow
	 *     Top returns Pow
	 *     Top.Pow_1_0_0_1 returns Pow
	 *     Top.Mod_1_0_1_1 returns Pow
	 *     Primary returns Pow
	 *     Parenthesis returns Pow
	 *
	 * Constraint:
	 *     (left=Top_Pow_1_0_0_1 right=Primary)
	 */
	protected void sequence_Top(ISerializationContext context, Pow semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.POW__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.POW__LEFT));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.POW__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.POW__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTopAccess().getPowLeftAction_1_0_0_1(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getTopAccess().getRightPrimaryParserRuleCall_1_1_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Let
	 *     Exp.Plus_1_0_0_1 returns Let
	 *     Exp.Minus_1_0_1_1 returns Let
	 *     Factor returns Let
	 *     Factor.Mult_1_0_0_1 returns Let
	 *     Factor.Div_1_0_1_1 returns Let
	 *     Top returns Let
	 *     Top.Pow_1_0_0_1 returns Let
	 *     Top.Mod_1_0_1_1 returns Let
	 *     Primary returns Let
	 *     VariableBinding returns Let
	 *     Parenthesis returns Let
	 *
	 * Constraint:
	 *     (id=ID binding=Exp body=Exp)
	 */
	protected void sequence_VariableBinding(ISerializationContext context, Let semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.LET__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.LET__ID));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.LET__BINDING) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.LET__BINDING));
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.LET__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.LET__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableBindingAccess().getIdIDTerminalRuleCall_2_0(), semanticObject.getId());
		feeder.accept(grammarAccess.getVariableBindingAccess().getBindingExpParserRuleCall_4_0(), semanticObject.getBinding());
		feeder.accept(grammarAccess.getVariableBindingAccess().getBodyExpParserRuleCall_6_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Exp returns Var
	 *     Exp.Plus_1_0_0_1 returns Var
	 *     Exp.Minus_1_0_1_1 returns Var
	 *     Factor returns Var
	 *     Factor.Mult_1_0_0_1 returns Var
	 *     Factor.Div_1_0_1_1 returns Var
	 *     Top returns Var
	 *     Top.Pow_1_0_0_1 returns Var
	 *     Top.Mod_1_0_1_1 returns Var
	 *     Primary returns Var
	 *     VariableUse returns Var
	 *     Parenthesis returns Var
	 *
	 * Constraint:
	 *     id=ID
	 */
	protected void sequence_VariableUse(ISerializationContext context, Var semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MathCompilerPackage.Literals.VAR__ID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MathCompilerPackage.Literals.VAR__ID));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableUseAccess().getIdIDTerminalRuleCall_1_0(), semanticObject.getId());
		feeder.finish();
	}
	
	
}
