/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mathcompiler.ui.internal.MathcompilerActivator;

public class MathCompilerUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathcompilerActivator.getInstance().getInjector("org.xtext.example.mydsl.MathCompiler");
	}

}
