/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.mathCompiler.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.mathCompiler.AbstractExpression;
import org.xtext.example.mydsl.mathCompiler.MathCompilerPackage;
import org.xtext.example.mydsl.mathCompiler.MathExp;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Math Exp</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mathCompiler.impl.MathExpImpl#getAbstractExpression <em>Abstract Expression</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MathExpImpl extends MinimalEObjectImpl.Container implements MathExp
{
  /**
   * The cached value of the '{@link #getAbstractExpression() <em>Abstract Expression</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbstractExpression()
   * @generated
   * @ordered
   */
  protected EList<AbstractExpression> abstractExpression;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MathExpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathCompilerPackage.Literals.MATH_EXP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AbstractExpression> getAbstractExpression()
  {
    if (abstractExpression == null)
    {
      abstractExpression = new EObjectContainmentEList<AbstractExpression>(AbstractExpression.class, this, MathCompilerPackage.MATH_EXP__ABSTRACT_EXPRESSION);
    }
    return abstractExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MathCompilerPackage.MATH_EXP__ABSTRACT_EXPRESSION:
        return ((InternalEList<?>)getAbstractExpression()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MathCompilerPackage.MATH_EXP__ABSTRACT_EXPRESSION:
        return getAbstractExpression();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MathCompilerPackage.MATH_EXP__ABSTRACT_EXPRESSION:
        getAbstractExpression().clear();
        getAbstractExpression().addAll((Collection<? extends AbstractExpression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MathCompilerPackage.MATH_EXP__ABSTRACT_EXPRESSION:
        getAbstractExpression().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MathCompilerPackage.MATH_EXP__ABSTRACT_EXPRESSION:
        return abstractExpression != null && !abstractExpression.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MathExpImpl
