/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.mathcompiler.ui.internal.MathcompilerActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathCompilerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MathcompilerActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MathcompilerActivator activator = MathcompilerActivator.getInstance();
		return activator != null ? activator.getInjector(MathcompilerActivator.ORG_XTEXT_EXAMPLE_MYDSL_MATHCOMPILER) : null;
	}

}
