/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MathCompilerUiModule extends AbstractMathCompilerUiModule {

	public MathCompilerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
